#line 2 "preprocess.c"

#line 4 "preprocess.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 142
#define YY_END_OF_BUFFER 143
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[449] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   43,    0,    0,
      143,  141,    1,  140,  141,  115,  110,  111,  112,  134,
      121,  122,  131,  128,  120,  129,  116,  130,  139,  133,
        4,  127,  125,  132,  137,  137,  137,  113,  114,  136,
      117,  138,  138,  138,  138,  138,  138,  138,  138,  138,

      138,  138,  118,  135,  119,   13,   14,   13,    5,    6,
       15,   16,  142,    9,    8,  142,  142,   19,   23,   23,
      142,  142,   35,   39,   39,   27,  142,  142,   28,   26,
       32,   32,  142,  142,   46,   50,   50,  142,  142,   52,
       56,   56,  142,  142,   65,   69,   69,   58,  142,  142,
       59,   63,   63,   71,   72,   74,  142,  142,   75,   79,
       79,   81,  142,  142,   82,   86,   86,   88,  142,  142,
       89,   93,   93,   95,  142,  142,   96,  100,  100,   44,
       43,  103,  106,  142,  105,    1,    2,    0,    0,    3,
      125,  134,  131,    0,   11,  130,  139,  124,  126,  125,

      123,  137,  137,    0,  137,    0,    0,    0,    0,    0,
        0,    0,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  135,   12,    8,    0,
       20,   19,   22,    0,   36,   35,   38,   27,    0,   29,
       28,   31,    0,   47,   46,   49,    0,   53,   52,   55,
        0,   66,   65,   68,   58,    0,   60,   59,   62,   71,
       74,    0,   76,   75,   78,   81,    0,   83,   82,   85,
       88,    0,   90,   89,   92,   95,    0,   97,   96,   99,
       43,  103,    0,   10,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   18,  138,  138,  138,  138,  138,

      138,  138,  138,  138,  138,    7,  138,  138,  138,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      104,  107,    0,    0,    0,   17,    0,    0,    0,    0,
        0,  138,  138,   34,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,   21,   37,   30,   48,   54,   67,
       61,   77,   84,   91,   98,    0,    0,    0,    0,    0,
       33,    0,    0,    0,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,   25,    0,    0,    0,    0,
        0,    0,    0,   24,  138,  138,    0,  138,   42,   51,
      138,  138,  138,  138,  138,  109,    0,    0,    0,    0,

        0,    0,  138,  138,  108,   41,  138,  138,    0,  138,
      138,    0,    0,    0,    0,   40,    0,  138,  138,  138,
      138,   45,    0,  138,  138,   87,   80,    0,    0,    0,
      138,  138,    0,  138,  138,   94,  101,   73,  102,    0,
       70,  138,    0,  138,    0,   57,   64,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    8,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   26,   25,   25,   25,   27,
       25,   25,   25,   25,   28,   25,   25,   25,   25,   29,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       30,    1,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   43,   50,   51,   52,   53,   54,   43,   55,
       56,   43,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[476] =
    {   0,
        0,    0,   57,   58,  630,  629,  628,  627,  626,  625,
       59,   60,   61,   62,   64,   65,   63,   66,   85,   89,
       86,   92,   93,   95,  106,  112,   99,  115,  118,  119,
      120,  121,  124,  127,  141,  145,  132,  148,  150,  155,
      162,  166,  169,  172,  171,  176,  183,  185,  188,  197,
      192,  198,  205,  211,  209,  214,  624,  623,  216,  219,
      625,  634,  238,  634,  242,  634,  634,  634,  634,  614,
      634,  634,  610,  634,  634,  634,  588,  116,  602,  634,
      634,   49,   95,  597,  223,  239,  245,  634,  634,  634,
      243,  568,  126,  570,  583,  561,    0,  568,  572,  230,

      575,  167,  634,  554,  634,  634,  634,  593,  634,  634,
      634,  634,  634,  634,  607,  571,  595,    0,  634,  589,
      568,  592,    0,  634,  586,   99,  565,  589,    0,  634,
      634,  583,  562,  586,    0,  634,  580,  559,  583,    0,
      634,  577,  556,  580,    0,  634,  574,  228,  553,  577,
        0,  634,  571,  232,  634,  233,  550,  574,    0,  634,
      568,  253,  547,  571,    0,  634,  565,  276,  544,  568,
        0,  634,  562,  284,  541,  565,    0,  634,  559,  634,
      573,  570,  634,  572,  634,  293,  634,  297,  560,  634,
      285,  562,  558,  519,  634,  551,  549,  634,  634,  286,

      634,  278,  294,  531,  299,  184,  515,  517,  530,  516,
      517,  524,    0,  514,  523,  513,  505,  504,   48,  501,
      272,  520,  507,  504,  517,  512,  491,  634,  545,  500,
      634,    0,  634,  499,  634,    0,  634,  307,  498,  634,
        0,  634,  497,  634,    0,  634,  496,  634,    0,  634,
      495,  634,    0,  634,  327,  494,  634,    0,  634,  329,
      331,  493,  634,    0,  634,  336,  492,  634,    0,  634,
      337,  491,  634,    0,  634,  341,  490,  634,    0,  634,
      533,  530,  531,  634,  487,  484,  483,  492,  483,  483,
      475,  490,  491,  490,    0,  475,  477,  487,  470,  474,

      476,  479,  468,  477,  458,    0,  463,  460,  462,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      479,  634,  453,  452,  454,  634,  450,  460,  448,  436,
      439,  445,  447,    0,  454,  434,  439,  434,  439,  441,
      215,  444,  447,  475,  634,  634,  634,  634,  634,  634,
      634,  634,  634,  634,  634,  477,  430,  429,  436,  433,
      634,  421,  434,  438,  423,  419,  450,  431,  429,  446,
      417,  424,  413,  420,  425,    0,  277,  410,  409,  417,
      406,  419,  413,  634,  404,  411,  325,  414,    0,  634,
      401,  409,  331,  411,  400,  634,  396,  394,  390,  397,

      398,  395,  379,  379,  634,    0,  373,  369,  332,  373,
      370,  347,  346,  314,  316,  634,  318,  342,  314,  340,
      308,  634,  310,  320,  308,  634,  634,  335,  307,  316,
      338,  317,  272,  290,  226,  634,  634,  634,  634,  214,
      634,  126,  106,  129,  108,  634,  634,  634,  368,  371,
      374,  377,  380,  383,  386,  389,  392,  395,  398,  401,
      404,  407,  410,  123,  413,  416,  419,  422,  425,  428,
      431,  434,  437,  440,  443
    } ;

static const flex_int16_t yy_def[476] =
    {   0,
      448,    1,  449,  449,  450,  450,  451,  451,  452,  452,
      452,  452,  453,  453,  452,  452,  454,  454,  452,  452,
      455,  455,  452,  452,  456,  456,  452,  452,  457,  457,
      452,  452,  458,  458,  452,  452,  459,  459,  452,  452,
      452,  452,  460,  460,  452,  452,  461,  461,  452,  452,
      462,  462,  452,  452,  463,  463,  452,  452,  452,  452,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  464,  464,  464,  464,  464,  464,  464,  464,  464,

      464,  464,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  465,  448,  448,
      448,  448,  466,  448,  448,  448,  448,  448,  467,  448,
      448,  448,  448,  448,  468,  448,  448,  448,  448,  469,
      448,  448,  448,  448,  470,  448,  448,  448,  448,  448,
      471,  448,  448,  448,  448,  448,  448,  448,  472,  448,
      448,  448,  448,  448,  473,  448,  448,  448,  448,  448,
      474,  448,  448,  448,  448,  448,  475,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,

      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  448,  448,  448,  448,
      448,  465,  448,  448,  448,  466,  448,  448,  448,  448,
      467,  448,  448,  448,  468,  448,  448,  448,  469,  448,
      448,  448,  470,  448,  448,  448,  448,  471,  448,  448,
      448,  448,  448,  472,  448,  448,  448,  448,  473,  448,
      448,  448,  448,  474,  448,  448,  448,  448,  475,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  464,  464,  464,  464,  464,  464,

      464,  464,  464,  464,  464,  464,  464,  464,  464,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  448,  448,  448,  448,
      448,  448,  448,  448,  464,  464,  448,  464,  464,  448,
      464,  464,  464,  464,  464,  448,  448,  448,  448,  448,

      448,  448,  464,  464,  448,  464,  464,  464,  448,  464,
      464,  448,  448,  448,  448,  448,  448,  464,  464,  464,
      464,  448,  448,  464,  464,  448,  448,  448,  448,  448,
      464,  464,  448,  464,  464,  448,  448,  448,  448,  448,
      448,  464,  448,  464,  448,  448,  448,    0,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448
    } ;

static const flex_int16_t yy_nxt[694] =
    {   0,
       62,   63,   64,   65,   63,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   83,   84,   85,   86,   85,   85,   87,   88,
       89,   90,   91,   92,   93,   94,   95,   96,   97,   97,
       97,   98,   97,   97,   99,   97,   97,   97,  100,  101,
      102,   97,   97,   97,   97,   97,  103,  104,  105,  107,
      107,  116,  116,  113,  113,  113,  121,  121,  113,  108,
      108,  198,  199,  120,  120,  125,  117,  117,  125,  118,
      118,  122,  122,  300,  123,  123,  126,  127,  113,  126,
      126,  127,  301,  126,  113,  133,  200,  133,  132,  200,

      238,  138,  128,  238,  132,  129,  128,  130,  113,  129,
      134,  130,  134,  135,  113,  135,  139,  138,  137,  140,
      113,  113,  143,  143,  137,  213,  113,  447,  195,  113,
      142,  142,  139,  196,  113,  140,  147,  144,  144,  147,
      145,  145,  148,  149,  153,  148,  148,  149,  446,  148,
      113,  154,  155,  204,  154,  445,  154,  155,  150,  154,
      153,  151,  150,  156,  157,  151,  156,  156,  157,  215,
      156,  113,  162,  163,  113,  162,  444,  162,  163,  158,
      162,  161,  159,  158,  161,  113,  159,  113,  164,  168,
      169,  165,  168,  164,  113,  167,  165,  167,  168,  169,

      113,  168,  224,  225,  173,  170,  174,  175,  171,  174,
      173,  113,  174,  175,  170,  174,  113,  171,  226,  287,
      182,  179,  176,  182,  288,  177,  179,  183,  176,  255,
      185,  177,  255,  260,  261,  184,  260,  261,  184,  186,
      187,  188,  186,  188,  187,  188,  188,  202,  202,  202,
      202,  202,  373,  374,  266,  189,  206,  266,  190,  189,
      191,  443,  190,  202,  202,  202,  203,  202,  221,  202,
      202,  205,  202,  202,  222,  442,  207,  271,  208,  209,
      271,  377,  204,  206,  210,  276,  200,  200,  276,  200,
      200,  211,  396,  212,  186,  187,  188,  186,  188,  187,

      188,  188,  202,  202,  202,  202,  202,  303,  238,  441,
      189,  238,  304,  190,  189,  191,  440,  190,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  255,  286,
      260,  255,  261,  260,  287,  261,  436,  266,  271,  288,
      266,  271,  276,  387,  405,  276,  409,  409,  439,  409,
      409,  422,  438,  437,  436,  435,  434,  433,  432,  427,
      431,  426,  430,  429,  428,  427,  426,  423,  106,  106,
      106,  109,  109,  109,  111,  111,  111,  113,  113,  113,
      119,  119,  119,  124,  124,  124,  131,  131,  131,  136,
      136,  136,  141,  141,  141,  146,  146,  146,  152,  152,

      152,  160,  160,  160,  166,  166,  166,  172,  172,  172,
      178,  178,  178,  232,  425,  232,  236,  424,  236,  241,
      421,  241,  245,  420,  245,  249,  419,  249,  253,  418,
      253,  258,  417,  258,  264,  416,  264,  269,  415,  269,
      274,  414,  274,  279,  413,  279,  412,  411,  410,  408,
      407,  406,  404,  403,  402,  401,  400,  399,  398,  397,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  379,  378,  283,  377,
      376,  375,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,

      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  282,  281,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  229,  227,  309,
      308,  307,  306,  305,  302,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  286,  197,  196,  285,
      193,  192,  284,  283,  282,  281,  280,  278,  277,  275,
      273,  272,  270,  268,  267,  265,  263,  262,  259,  257,
      256,  254,  252,  251,  250,  248,  247,  246,  244,  243,

      242,  240,  239,  237,  235,  234,  233,  231,  230,  229,
      228,  227,  223,  220,  219,  218,  217,  216,  214,  201,
      197,  194,  193,  192,  448,  181,  180,  115,  114,  112,
      112,  110,  110,   61,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448

    } ;

static const flex_int16_t yy_chk[694] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   11,   12,   13,   14,   17,   15,   16,   18,    3,
        4,   82,   82,   13,   14,   17,   11,   12,   18,   11,
       12,   15,   16,  219,   15,   16,   19,   19,   21,   19,
       20,   20,  219,   20,   22,   23,   83,   24,   21,   83,

      126,   27,   19,  126,   22,   19,   20,   19,   25,   20,
       23,   20,   24,   23,   26,   24,   27,   28,   25,   27,
       29,   30,   31,   32,   26,  464,   33,  445,   78,   34,
       29,   30,   28,   78,   37,   28,   33,   31,   32,   34,
       31,   32,   35,   35,   37,   35,   36,   36,  444,   36,
       38,   39,   39,   93,   39,  443,   40,   40,   35,   40,
       38,   35,   36,   41,   41,   36,   41,   42,   42,   93,
       42,   43,   45,   45,   44,   45,  442,   46,   46,   41,
       46,   43,   41,   42,   44,   47,   42,   48,   45,   49,
       49,   45,   49,   46,   51,   47,   46,   48,   50,   50,

       52,   50,  102,  102,   51,   49,   53,   53,   49,   53,
       52,   55,   54,   54,   50,   54,   56,   50,  102,  206,
       59,   55,   53,   60,  206,   53,   56,   59,   54,  148,
       60,   54,  148,  154,  156,   59,  154,  156,   60,   63,
       63,   63,   63,   65,   65,   65,   65,   85,   85,   85,
       85,   85,  341,  341,  162,   63,  100,  162,   63,   65,
       63,  440,   65,   86,   86,   86,   86,   86,  100,   87,
       87,   87,   87,   87,  100,  435,   91,  168,   91,   91,
      168,  377,   86,   87,   91,  174,  191,  200,  174,  191,
      200,   91,  377,   91,  186,  186,  186,  186,  188,  188,

      188,  188,  202,  202,  202,  202,  202,  221,  238,  434,
      186,  238,  221,  186,  188,  186,  433,  188,  203,  203,
      203,  203,  203,  205,  205,  205,  205,  205,  255,  203,
      260,  255,  261,  260,  205,  261,  432,  266,  271,  205,
      266,  271,  276,  387,  387,  276,  393,  409,  431,  393,
      409,  409,  430,  429,  428,  425,  424,  423,  421,  420,
      419,  418,  417,  415,  414,  413,  412,  409,  449,  449,
      449,  450,  450,  450,  451,  451,  451,  452,  452,  452,
      453,  453,  453,  454,  454,  454,  455,  455,  455,  456,
      456,  456,  457,  457,  457,  458,  458,  458,  459,  459,

      459,  460,  460,  460,  461,  461,  461,  462,  462,  462,
      463,  463,  463,  465,  411,  465,  466,  410,  466,  467,
      408,  467,  468,  407,  468,  469,  404,  469,  470,  403,
      470,  471,  402,  471,  472,  401,  472,  473,  400,  473,
      474,  399,  474,  475,  398,  475,  397,  395,  394,  392,
      391,  388,  386,  385,  383,  382,  381,  380,  379,  378,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  360,  359,  358,  357,  356,  344,
      343,  342,  340,  339,  338,  337,  336,  335,  333,  332,
      331,  330,  329,  328,  327,  325,  324,  323,  321,  320,

      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  283,  282,  281,  277,  272,  267,  262,
      256,  251,  247,  243,  239,  234,  230,  229,  227,  226,
      225,  224,  223,  222,  220,  218,  217,  216,  215,  214,
      212,  211,  210,  209,  208,  207,  204,  197,  196,  194,
      193,  192,  189,  184,  182,  181,  179,  176,  175,  173,
      170,  169,  167,  164,  163,  161,  158,  157,  153,  150,
      149,  147,  144,  143,  142,  139,  138,  137,  134,  133,

      132,  128,  127,  125,  122,  121,  120,  117,  116,  115,
      108,  104,  101,   99,   98,   96,   95,   94,   92,   84,
       79,   77,   73,   70,   61,   58,   57,   10,    9,    8,
        7,    6,    5,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "preprocess.lex"
#line 2 "preprocess.lex"
#include <stdlib.h>
int linenumber=1;
//void yyerror(char *);
#line 753 "preprocess.c"

#line 755 "preprocess.c"

#define INITIAL 0
#define mcomment 1
#define scomment 2
#define endmcomment 3
#define comment 4
#define asm 5
#define asm_mcomment 6
#define data 7
#define data_mcomment 8
#define sdata 9
#define sdata_mcomment 10
#define player 11
#define player_mcomment 12
#define lives 13
#define lives_mcomment 14
#define playercolor 15
#define playercolor_mcomment 16
#define scorecolors 17
#define scorecolors_mcomment 18
#define pffirstline 19
#define playfield 20
#define playfield_mcomment 21
#define pfcolors 22
#define pfcolors_mcomment 23
#define bkcolors 24
#define bkcolors_mcomment 25
#define pfheights 26
#define pfheights_mcomment 27
#define includes 28
#define collision 29

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "preprocess.lex"

#line 1006 "preprocess.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 449 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 634 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "preprocess.lex"
putchar(' ');
	YY_BREAK
case 2:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 37 "preprocess.lex"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "preprocess.lex"
{BEGIN(scomment);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "preprocess.lex"
{BEGIN(scomment);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "preprocess.lex"
;
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 42 "preprocess.lex"
{linenumber++;printf("\n");BEGIN(INITIAL);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "preprocess.lex"
{printf("rem");BEGIN(comment);}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 45 "preprocess.lex"
printf("%s",yytext);
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 46 "preprocess.lex"
{linenumber++;printf("\n");BEGIN(INITIAL);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "preprocess.lex"
{BEGIN(mcomment);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "preprocess.lex"
{BEGIN(mcomment);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "preprocess.lex"
{BEGIN(INITIAL);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "preprocess.lex"
;
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 52 "preprocess.lex"
{linenumber++; printf("\n");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "preprocess.lex"
;
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 55 "preprocess.lex"
{linenumber++;BEGIN(INITIAL);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "preprocess.lex"
{printf("%s",yytext);BEGIN(asm);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "preprocess.lex"
;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "preprocess.lex"
{BEGIN(asm_mcomment);}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 61 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "preprocess.lex"
{BEGIN(asm);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "preprocess.lex"
;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "preprocess.lex"
{printf("%s",yytext);BEGIN(sdata);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "preprocess.lex"
putchar(' ');
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "preprocess.lex"
;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "preprocess.lex"
{BEGIN(sdata_mcomment);}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 71 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "preprocess.lex"
{BEGIN(sdata);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "preprocess.lex"
;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "preprocess.lex"
{printf("%s",yytext);BEGIN(data);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "preprocess.lex"
;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "preprocess.lex"
{BEGIN(data_mcomment);}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 79 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "preprocess.lex"
{BEGIN(data);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "preprocess.lex"
;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "preprocess.lex"
{printf("%s",yytext);BEGIN(includes);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "preprocess.lex"
{printf("%s",yytext);BEGIN(includes);}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 86 "preprocess.lex"
printf("%s",yytext);
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 87 "preprocess.lex"
{linenumber++;printf("\n");BEGIN(INITIAL);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 89 "preprocess.lex"
{printf("%s",yytext);BEGIN(player);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 90 "preprocess.lex"
;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 91 "preprocess.lex"
{BEGIN(player_mcomment);}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 92 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 93 "preprocess.lex"
{BEGIN(player);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 94 "preprocess.lex"
;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 96 "preprocess.lex"
{printf("%s",yytext);BEGIN(lives);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 97 "preprocess.lex"
;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 98 "preprocess.lex"
{BEGIN(lives_mcomment);}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 99 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "preprocess.lex"
{BEGIN(lives);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "preprocess.lex"
;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 103 "preprocess.lex"
{printf("%s",yytext);BEGIN(scorecolors);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 104 "preprocess.lex"
;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 105 "preprocess.lex"
;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 106 "preprocess.lex"
{BEGIN(scorecolors_mcomment);}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 107 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 108 "preprocess.lex"
{BEGIN(scorecolors);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 109 "preprocess.lex"
;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 111 "preprocess.lex"
{printf("%s",yytext);BEGIN(playercolor);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 112 "preprocess.lex"
;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 113 "preprocess.lex"
{BEGIN(playercolor_mcomment);}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 114 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 115 "preprocess.lex"
{BEGIN(playercolor);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 116 "preprocess.lex"
;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 118 "preprocess.lex"
{printf("%s",yytext);BEGIN(pffirstline);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 120 "preprocess.lex"
printf(" ");
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 121 "preprocess.lex"
{linenumber++;printf("\n");BEGIN(playfield);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 123 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 124 "preprocess.lex"
;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "preprocess.lex"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "preprocess.lex"
{BEGIN(playfield_mcomment);}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 127 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "preprocess.lex"
{BEGIN(playfield);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 129 "preprocess.lex"
;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 131 "preprocess.lex"
{printf("%s",yytext);BEGIN(pfcolors);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 132 "preprocess.lex"
printf(" ");
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 133 "preprocess.lex"
;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 134 "preprocess.lex"
{BEGIN(pfcolors_mcomment);}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 135 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 136 "preprocess.lex"
{BEGIN(pfcolors);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 137 "preprocess.lex"
;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "preprocess.lex"
{printf("%s",yytext);BEGIN(bkcolors);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 140 "preprocess.lex"
printf(" ");
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 141 "preprocess.lex"
;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 142 "preprocess.lex"
{BEGIN(bkcolors_mcomment);}
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 143 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 144 "preprocess.lex"
{BEGIN(bkcolors);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 145 "preprocess.lex"
;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 147 "preprocess.lex"
{printf("%s",yytext);BEGIN(pfheights);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 148 "preprocess.lex"
printf(" ");
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "preprocess.lex"
;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "preprocess.lex"
{BEGIN(pfheights_mcomment);}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 151 "preprocess.lex"
{linenumber++;printf("\nend");BEGIN(INITIAL);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "preprocess.lex"
{BEGIN(pfheights);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "preprocess.lex"
;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 155 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 156 "preprocess.lex"
{printf("%s",yytext);BEGIN(collision);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 157 "preprocess.lex"

	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 158 "preprocess.lex"
{fprintf(stderr,"%d: Missing )\n",linenumber);exit(1);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 159 "preprocess.lex"
printf("%s",yytext);
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 160 "preprocess.lex"
{printf("%s",yytext);BEGIN(INITIAL);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 162 "preprocess.lex"
printf("%s",yytext);
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 163 "preprocess.lex"
printf("%s",yytext);
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 164 "preprocess.lex"
printf("step -");
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 165 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 166 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 167 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 168 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 169 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 170 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 171 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 172 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 173 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 174 "preprocess.lex"
printf("%s", yytext);
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 177 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 178 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 179 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 180 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 181 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 182 "preprocess.lex"
printf(" = ");
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 183 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 184 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 185 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 186 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 187 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 188 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 189 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 190 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 191 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 192 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 193 "preprocess.lex"
printf(" %s ", yytext);
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 195 "preprocess.lex"
printf("%s",yytext);
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 196 "preprocess.lex"
{       printf("%s", yytext);}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 197 "preprocess.lex"
{       printf("%s", yytext);}
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 198 "preprocess.lex"
{printf("\n"); linenumber++;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 199 "preprocess.lex"
{fprintf(stderr,"(%d) Parse error: unrecognized character \"%s\"\n",linenumber,yytext);  exit(1);}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 200 "preprocess.lex"
ECHO;
	YY_BREAK
#line 1798 "preprocess.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(mcomment):
case YY_STATE_EOF(scomment):
case YY_STATE_EOF(endmcomment):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(asm):
case YY_STATE_EOF(asm_mcomment):
case YY_STATE_EOF(data):
case YY_STATE_EOF(data_mcomment):
case YY_STATE_EOF(sdata):
case YY_STATE_EOF(sdata_mcomment):
case YY_STATE_EOF(player):
case YY_STATE_EOF(player_mcomment):
case YY_STATE_EOF(lives):
case YY_STATE_EOF(lives_mcomment):
case YY_STATE_EOF(playercolor):
case YY_STATE_EOF(playercolor_mcomment):
case YY_STATE_EOF(scorecolors):
case YY_STATE_EOF(scorecolors_mcomment):
case YY_STATE_EOF(pffirstline):
case YY_STATE_EOF(playfield):
case YY_STATE_EOF(playfield_mcomment):
case YY_STATE_EOF(pfcolors):
case YY_STATE_EOF(pfcolors_mcomment):
case YY_STATE_EOF(bkcolors):
case YY_STATE_EOF(bkcolors_mcomment):
case YY_STATE_EOF(pfheights):
case YY_STATE_EOF(pfheights_mcomment):
case YY_STATE_EOF(includes):
case YY_STATE_EOF(collision):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 449 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 449 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 448);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "preprocess.lex"

  int yywrap(void) {      return 1;  }
int main(){yylex();}

